/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;


import DAO.UtilisateurDAO;

import Metier.Utilisateur;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author coolye
 */
public class ListeSalarieVal extends javax.swing.JFrame {

    /**
     * Creates new form listeSalarie
     */

    public ListeSalarieVal() throws SQLException {
        initComponents();
        UtilisateurDAO utilisateurDAO = new UtilisateurDAO();
        ArrayList<Utilisateur> listUtilisateur = utilisateurDAO.listUtilisateur();
        
        JTable jTable_Utilisateur = tabSalarieAttente;
        DefaultTableModel dm = (DefaultTableModel) jTable_Utilisateur.getModel();
        for(Utilisateur listUtilisateur1 : listUtilisateur){
            Utilisateur oneUtilisateur = utilisateurDAO.readOneUtilisateur(listUtilisateur1.getId_Utilisateur());
            String a[] = {Integer.toString(oneUtilisateur.getId_Utilisateur()), oneUtilisateur.getNom_Utilisateur(), oneUtilisateur.getPrenom_Utilisateur(), oneUtilisateur.getMail_Utilisateur()};
            dm.addRow(a);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabSalarieAttente = new javax.swing.JTable();
        butRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitre.setText("Liste de tout les salaries");

        tabSalarieAttente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabSalarieAttente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSalarieAttenteMouseClicked(evt);
            }
        });
        tabSalarieAttente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabSalarieAttenteComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabSalarieAttente);

        butRetour.setText("Retour");
        butRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(labelTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butRetour)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelTitre)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butRetour)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRetourActionPerformed
        MenuSalarie uneFenetre = new MenuSalarie();
        uneFenetre.setVisible(true);
        ListeSalarieVal.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_butRetourActionPerformed

    private void tabSalarieAttenteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabSalarieAttenteComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabSalarieAttenteComponentShown

    private void tabSalarieAttenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSalarieAttenteMouseClicked

    //on récupérele numero de la ligne cliqué
        int ligneSelectionne = tabSalarieAttente.getSelectedRow();
    //on récupère la valeur de la  colonne souhaité de la ligne sélectionné (mettre id dans la dernière colonne chez moi 5 et lui mettre 0 en largeur min et max pour la rendre invisible)
        String Id_Jtable1=(String) tabSalarieAttente.getValueAt(ligneSelectionne,0);
    //convertir en string en int
        int id_Jtable= Integer.parseInt(Id_Jtable1);
    //vérifier si réception dans le log
        System.out.println(id_Jtable);
    //ouvrir la fenêtre visé avec l'id en ref
        DetailSalarie uneFenetre = null;
        try {
            uneFenetre = new DetailSalarie(id_Jtable);
        } catch (SQLException ex) {
            Logger.getLogger(ListeSalarieAtt.class.getName()).log(Level.SEVERE, null, ex);
        }
        uneFenetre.setVisible(true);
        ListeSalarieVal.this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_tabSalarieAttenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListeSalarieVal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListeSalarieVal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butRetour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTable tabSalarieAttente;
    // End of variables declaration//GEN-END:variables
}
