/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author coolye
 */
public class MenuSalarie extends javax.swing.JFrame {

    /**
     * Creates new form MenuSalarie
     */
    public MenuSalarie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButSalNoteAtt = new javax.swing.JButton();
        butListedessalarie = new javax.swing.JButton();
        LabTitre = new javax.swing.JLabel();
        ButRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButSalNoteAtt.setText("Salariés - Note en attente de validation");
        ButSalNoteAtt.setMaximumSize(new java.awt.Dimension(115, 25));
        ButSalNoteAtt.setMinimumSize(new java.awt.Dimension(115, 25));
        ButSalNoteAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalNoteAttActionPerformed(evt);
            }
        });

        butListedessalarie.setText("Salarie - tous les salarie");
        butListedessalarie.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        butListedessalarie.setMaximumSize(new java.awt.Dimension(115, 25));
        butListedessalarie.setMinimumSize(new java.awt.Dimension(115, 25));
        butListedessalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListedessalarieActionPerformed(evt);
            }
        });

        LabTitre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabTitre.setText("Gestion des Salariés");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ButSalNoteAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butListedessalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(LabTitre)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSalNoteAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butListedessalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ButRetour.setText("Retour");
        ButRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButRetour)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(ButRetour)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButSalNoteAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalNoteAttActionPerformed
        ListeSalarieAtt uneFenetre = null;
        try {
            uneFenetre = new ListeSalarieAtt();
        } catch (SQLException ex) {
            Logger.getLogger(MenuSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
        uneFenetre.setVisible(true);
        MenuSalarie.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_ButSalNoteAttActionPerformed

    private void butListedessalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListedessalarieActionPerformed
        ListeSalarieVal uneFenetre = null;
        try {
            uneFenetre = new ListeSalarieVal();
        } catch (SQLException ex) {
            Logger.getLogger(MenuSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
        uneFenetre.setVisible(true);
        MenuSalarie.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_butListedessalarieActionPerformed

    private void ButRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRetourActionPerformed
        Menu uneFenetre = new Menu();
        uneFenetre.setVisible(true);
        MenuSalarie.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_ButRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSalarie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButRetour;
    private javax.swing.JButton ButSalNoteAtt;
    private javax.swing.JLabel LabTitre;
    private javax.swing.JButton butListedessalarie;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
